### ISSUE TITLE
Trouble with case sensitivity of table names and column names

### ISSUE THREAD

**Issue by jdschreck** [strongloop/loopback-connector-db2#13]
We have a StrongLoop api that we are currently using to access a MYSQL
database. We are trying to move this application to Bluemix. On Bluemix
we are trying to make use of a SQLDB (DB2) database. We have installed
the loopback-connector-db2, but we are having some problems. I suspect
that the main problem we are having has to do with case sensitivity. We
initially created some tables in the DB2 database without quoting them and
found that everything got capitalized (table names and column names). We
had a little success with editing our model json files to use capital
names, however, as we tried to expand our success to our other tables we
somehow broke something and even what had been working stopped working.

So, we took a step back and looked up how to maintain the case sensitivity
when we create the tables in the DB2 database and started with a fresh
copy of our model json files. Now the first error we got back in the
Explorer seems to indicate that the db2 connector is not correctly quoting
the table name which is "services" all lower case.

{
"error": {
"name": "Error",
"status": 500,
"message": "[IBM][CLI Driver][DB2/LINUXX8664] SQL0204N
\"USER14557.SERVICES\" is an undefined name. SQLSTATE=42704\n",
"errors": [],
"error": "[node-odbc] SQL_ERROR",
"state": "42S02",
"stack": "Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0204N
\"USER14557.SERVICES\" is an undefined name. SQLSTATE=42704\n\n at
Error (native)"
}
}

In our previous testing where we had some limited success, we achieved that by having to edit our model json to use capitalized names of fields.  That is why I believe we will have a problem with column names after this issue with the table name is resolved.

@qpresley - Strongloop support suggested I mention you on this issue.

**Comment by jdschreck** [comment]
@qpresley - I hacked my way around the issue with the database name and found that the mixed as column names seem to be handled correctly, so I think the issue is only with the database name.

I changed a few locations that were referencing this.schema and this.table(model) directly to call this.tableEscaped(model).  I also added toUpperCase() in the following assignment:

this.schema = settings.username.toUpperCase();

**Comment by qpresley** [comment]
@jdschreck I believe we have already fixed this.  Please feel free to validate before closing.

**Comment by qpresley** [comment]
Closing issue as I believe this is now fixed.

**Comment by ninoguba** [comment]
What was the fix exactly?  We're using the DB2 connector and there is still an issue with the exact casing of the table and column names.   We are forced to define our models with all uppercase model and property names for it to work successfully with a DB2 datasource.

This works fine for custom models we define but the big problem surfaces when we need to connect the built-in models to the same DB2 datasource.

It is also a problem since we define our custom APPUSER model using the built-in User model as the base.   This adds the other properties - realm, email, password, etc. - all in lower case.  This will result in an "undefined column" error message because it doesn't match the letter case.

**Comment by qpresley** [comment]
@ninoguba The fix for this was put in a while ago which deals with escaping the Database, Table and Column names in the code.

The issue you are describing is a bit different in that the column names are likely REALM, EMAIL, PASSWORD while the property names as you show are realm, email, password.  This is an effect of how DB2 process the "CREATE TABLE" statement.  If when you created those tables you did so with a statement similar to the following it would not work

CREATE TABLE sTuFf (realm char(20), email char(250), password char(16))

This doesn't work because DB2 will upper case the table name and the column names prior to creating the table.  This leaves you with two choices.  The first is that you can modify the JSON file for the built in models and add a columnName property that uses the correct case.  See https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#data-mapping-properties.  Or you can recreate the tables using a create statement similar to the following which will force DB2 to create the tables with the appropriate case.

CREATE  TABLE "\stuff\" (\"realm\" char(20), \"email\" char(250), \"password\" char(16))

**Comment by ninoguba** [comment]
Thanks @qpresley we'll try the 2nd choice this time.

I've tried the 1st choice yesterday and its a bit painful coz I have to track down where the User property is used in code and update those too.  Also if I do modify the built-in model's .json file how do I make sure they dont get overwritten when we do npm install/update?  I haven't been able to figure out successfully how to extend or redefine the built-in model properties in a boot script.  So far what I've tried doen't work.

**Comment by ninoguba** [comment]
Thanks again @qpresley we're now able to properly create our tables in DB2 that works well with our model definition.

Also thanks to that link I figured out how to exclude any of the properties of the built-in user model in my extended user model.  I totally missed that part in the documentation.
